/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
              "surface": "#0b1326",
              "primary": "#d0bcff",
              "on-error": "#690005",
              "error": "#ffb4ab",
              "surface-container": "#171f33",
              "surface-container-highest": "#2d3449",
              "background": "#0b1326",
              "primary-fixed": "#e9ddff",
              "on-secondary": "#002e6a",
              "tertiary-fixed-dim": "#dbb8ff",
              "on-tertiary-fixed-variant": "#573878",
              "secondary": "#adc6ff",
              "surface-container-lowest": "#060e20",
              "surface-container-high": "#222a3d",
              "on-primary": "#3c0091",
              "on-secondary-fixed-variant": "#004395",
              "on-primary-fixed-variant": "#5516be",
              "on-error-container": "#ffdad6",
              "inverse-on-surface": "#283044",
              "surface-variant": "#2d3449",
              "outline": "#958ea0",
              "inverse-primary": "#6d3bd7",
              "inverse-surface": "#dae2fd",
              "on-secondary-container": "#e6ecff",
              "on-tertiary-container": "#381959",
              "on-primary-fixed": "#23005c",
              "surface-tint": "#d0bcff",
              "surface-dim": "#0b1326",
              "on-primary-container": "#340080",
              "on-tertiary": "#3f2160",
              "secondary-container": "#0566d9",
              "secondary-fixed-dim": "#adc6ff",
              "secondary-fixed": "#d8e2ff",
              "tertiary-fixed": "#efdbff",
              "on-tertiary-fixed": "#29074a",
              "error-container": "#93000a",
              "on-surface": "#dae2fd",
              "on-background": "#dae2fd",
              "surface-container-low": "#131b2e",
              "on-surface-variant": "#cbc3d7",
              "surface-bright": "#31394d",
              "tertiary-container": "#a482c8",
              "tertiary": "#dbb8ff",
              "outline-variant": "#494454",
              "primary-container": "#a078ff",
              "primary-fixed-dim": "#d0bcff",
              "on-secondary-fixed": "#001a42"
      },
      "borderRadius": {
              "DEFAULT": "0.25rem",
              "lg": "0.5rem",
              "xl": "0.75rem",
              "full": "9999px"
      },
      "spacing": {
              "md": "16px",
              "sm": "8px",
              "gutter": "24px",
              "xxl": "80px",
              "lg": "24px",
              "xl": "40px",
              "container-max": "1200px",
              "unit": "4px",
              "xs": "4px"
      },
      "fontFamily": {
              "sans": ["Inter", "sans-serif"],
              "label-sm": ["Geist", "system-ui", "sans-serif"],
              "headline-lg": ["Inter", "sans-serif"],
              "headline-lg-mobile": ["Inter", "sans-serif"],
              "body-md": ["Inter", "sans-serif"],
              "mono-code": ["Geist Mono", "monospace"],
              "display-xl": ["Inter", "sans-serif"]
      },
      "fontSize": {
              "label-sm": ["12px", { "lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "500" }],
              "headline-lg": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
              "headline-lg-mobile": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
              "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
              "mono-code": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
              "display-xl": ["64px", { "lineHeight": "72px", "letterSpacing": "-0.02em", "fontWeight": "700" }]
      }
    },
  },
  plugins: [],
}
