"""Add video metadata and progress columns

Revision ID: e25aebbb2e68
Revises: 1a252b420170
Create Date: 2026-06-24 13:21:55.541248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e25aebbb2e68'
down_revision: Union[str, Sequence[str], None] = '1a252b420170'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('progress', sa.Float(), nullable=False, server_default='0.0'))
    op.add_column('jobs', sa.Column('video_title', sa.String(), nullable=True))
    op.add_column('jobs', sa.Column('video_thumbnail', sa.String(), nullable=True))
    op.add_column('jobs', sa.Column('video_duration', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'video_duration')
    op.drop_column('jobs', 'video_thumbnail')
    op.drop_column('jobs', 'video_title')
    op.drop_column('jobs', 'progress')
    # ### end Alembic commands ###
